name: Merge any release branch to uat
on:
  pull_request:
    types: [closed]

jobs:
  merge-branch:
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/')
    runs-on: ubuntu-latest
    steps:
      - name: echo Branch Name
        run: echo "${{ github.head_ref }} "
      
      - uses: actions/checkout@master

      - name: Merge release -> develop
        uses: devmasx/merge-branch@master
        with:
          target_branch: main
          github_token: ${{ github.token }}
        env:
          INPUT_MESSAGE: 'automerge from ${{ env.BRANCH_NAME }}'